#!/usr/bin/with-contenv bash

source /assets/functions/00-container
# shellcheck disable=SC2034
PROCESS_NAME="mongo"

if var_true "$ENABLE_XMPP" ;  then
	print_notice "Enabling MongoDB for XMPP support"

	if [ ! -d /var/lib/mongodb ]; then
    print_info "New database detected, setting up.."
	  mkdir -p /data/var/lib/mongodb /var/log/mongodb
  fi

  service_start 08-mongodb
else
	service_stop 08-mongodb	 
fi

liftoff