#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service 10-freepbx
# shellcheck disable=SC2034
PROCESS_NAME="mariadb"

if var_true "$DB_EMBEDDED" ;  then
  silent service mysql stop

  if [ ! -d /var/lib/mysql/mysql ]; then
    print_info "New embedded database detected, setting up.."
    mkdir -p /data/var/lib/mysql
    cp -R /assets/config/var/lib/mysql /data/var/lib
  fi

  chown -R mysql. /var/lib/mysql
  silent service mysql start
else
  print_info "No embedded database detected, skip.."
fi

liftoff